---
title       : Flower Species - Knowledge Base
subtitle    : Developing Data Products - Course Project
author      : Wong Yoke Yong
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Introduction

- This Application guesses which flower you are looking at
- Working Database include the following species:
        
        1) Setosa
        2) Versicolor
        3) Virginica

---

## Prediction Engine Used

Random Forests Algorithm is chosen, which provides 100% Accuracy

```{r, echo=FALSE}

require(datasets)
require(randomForest)
require(caret)

data(iris)
set.seed(100)
foldControl <- trainControl(method="cv", number=3)
modelFit0 <- train(Species ~ ., method = "rf", trControl=foldControl, data=iris)
predictor <- predict(modelFit0, iris)
confusionMatrix(iris$Species, predictor)

```

---

## Advantages

- Flowers, as per living things, come in different sizes
- A recognition system is needed to do a general classification of the flower
- Measurements are easy to collect and widely available
- Storage Space is cheap and huge amount of data can be stored
- Prediction algorithm can apply to different flower species that are added to the Database

---

## Caveat

- The sample size is too small; 3-Fold Cross Validation is used to check the accuracy
- Ongoing expansion of Working Database
- Botanical Research Team, headed by Dr. John Doe, will address this issue
